name: CI
on: push
jobs:
  mix_test:
    name: mix test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: _build
          key: test-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
    strategy:
      matrix:
        elixir: ["1.8.x", "1.9.x", "1.10.x", "1.11.x"]
        exclude:
          - elixir: "1.10.x"
            otp: "20.x"
          - elixir: "1.11.x"
            otp: "20.x"
        otp: [20.x, 21.x, 22.x, 23.x]
